#include <QCoreApplication>
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQuickStyle>
#include <QString>
#include <memory>

#include "ConsoleLogger.h"
#include "CommandService.h"
#include "AppContext.h"
#include "LocalStoreService.h"
#include "SecretsServiceStub.h"

using namespace Qt::StringLiterals;
using namespace Sofa::Core;

int main(int argc, char *argv[])
{
    QQuickStyle::setStyle("Basic");
    QGuiApplication app(argc, argv);

    // Bootstrap Services
    auto logger = std::make_shared<ConsoleLogger>();
    auto commandService = std::make_shared<CommandService>(logger);
    auto localStore = std::make_shared<LocalStoreService>(logger);
    auto secrets = std::make_shared<SecretsServiceStub>();

    // Register a test command
    commandService->registerCommand("test.hello", "Hello Command", [logger]() {
        logger->info("Hello from Command System!");
    });

    auto appContext = std::make_shared<AppContext>(commandService, logger, localStore, secrets);

    QQmlApplicationEngine engine;

    // Expose AppContext to QML
    engine.rootContext()->setContextProperty("App", appContext.get());

    // Using the standard path generated by qt_add_qml_module with URI "sofa.studio"
    // and file structure "qml/Main.qml"
    const QUrl url(u"qrc:/qt/qml/sofa/studio/qml/Main.qml"_s);
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreationFailed,
        &app, []() { QCoreApplication::exit(-1); },
        Qt::QueuedConnection);
    engine.load(url);

    return app.exec();
}
